server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://rm-bp149ki7cte7mesg62o.mysql.rds.aliyuncs.com:3306/authorization
    username: root
    password: Xhuicloud@123
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG