server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authorization
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG