server:
  port: 9090

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  datasource:
    url: jdbc:mysql://rm-bp149ki7cte7mesg62o.mysql.rds.aliyuncs.com:3306/authorization
    username: root
    password: Xhuicloud@123
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: debug
    org.springframework.web: INFO
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
#    org.springframework.boot.autoconfigure: DEBUG