server:
  port: 9092

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          gitee:
            client-id: 2274094e86ac40f6a401883715ae539d14be2e1dfe4552cfbb71b768ae8ea452
            client-secret: b5245ca84327ce890372c69745c639c8c0dd9a5916ec3f7fb5fed5485e8d8433
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
            scope: user_info
          client2-authorization-code:
            provider: spring
            client-id: client2
            client-secret: secret2
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9092/authorization"
            scope: message.read,message.write
            client-name: client2-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:8080